CREATE TABLE PokemonType(id INTEGER PRIMARY KEY, label TEXT NOT NULL, picture BLOB);
INSERT INTO PokemonType(id, label, picture) VALUES (1, 'normal', null);
INSERT INTO PokemonType(id, label, picture) VALUES (2, 'fighting', null);
INSERT INTO PokemonType(id, label, picture) VALUES (3, 'flying', null);
INSERT INTO PokemonType(id, label, picture) VALUES (4, 'poison', null);
INSERT INTO PokemonType(id, label, picture) VALUES (5, 'ground', null);
INSERT INTO PokemonType(id, label, picture) VALUES (6, 'rock', null);
INSERT INTO PokemonType(id, label, picture) VALUES (7, 'bug', null);
INSERT INTO PokemonType(id, label, picture) VALUES (8, 'ghost', null);
INSERT INTO PokemonType(id, label, picture) VALUES (9, 'steel', null);
INSERT INTO PokemonType(id, label, picture) VALUES (10, 'fire', null);
INSERT INTO PokemonType(id, label, picture) VALUES (11, 'water', null);
INSERT INTO PokemonType(id, label, picture) VALUES (12, 'grass', null);
INSERT INTO PokemonType(id, label, picture) VALUES (13, 'electric', null);
INSERT INTO PokemonType(id, label, picture) VALUES (14, 'psychic', null);
INSERT INTO PokemonType(id, label, picture) VALUES (15, 'ice', null);
INSERT INTO PokemonType(id, label, picture) VALUES (16, 'dragon', null);
INSERT INTO PokemonType(id, label, picture) VALUES (17, 'dark', null);
INSERT INTO PokemonType(id, label, picture) VALUES (18, 'fairy', null);
CREATE TABLE Pokemon(id INTEGER PRIMARY KEY, name TEXT NOT NULL, family TEXT NOT NULL, height REAL NOT NULL, weight REAL NOT NULL, type1 INTEGER NOT NULL, type2 INTEGER, description TEXT NOT NULL, image BLOB, FOREIGN KEY (type1) REFERENCES PokemonType(id), FOREIGN KEY (type2) REFERENCES PokemonType(id));